"""warlog-spec — canonical workflow contract for Security Operations.

The Python reference implementation. Import from here to integrate
with a Warlog runtime or any compatible orchestrator :

    from warlog_spec import (
        AbiConnector,
        ConnectorAbiError,
        ConnectorCapability,
        ResponseActionId,
        ResponseActionSpec,
        ResponseActionResult,
        ExecutionOutcome,
        FailureCategory,
    )

See ``README.md`` for the "Build a connector in 50 lines" guide.
"""

from warlog_spec.abi import AbiConnector, AbiEnricher, ConnectorAbiError
from warlog_spec.artifacts import (
    AcceptedRisk,
    AlternativeTechnique,
    ApprovalDecision,
    ApprovalDecisionPayload,
    ArbitrationAuthority,
    ArbitrationScope,
    ArtifactCitation,
    ArtifactConfidence,
    ArtifactEnvelope,
    ArtifactProducer,
    ArtifactReviewState,
    CanonicalArtifact,
    CaseReturnSummary,
    ClassificationAssessment,
    ClassificationDecision,
    ClosureSummary,
    ConfidenceBand,
    EnrichmentAssessment,
    EnrichmentAssessmentPayload,
    EnrichmentRequest,
    ExtractedIOC,
    MitreAssessment,
    MitreMapping,
    NormalizedEntity,
    PolicyRef,
    ResponseActionRequestRef,
    RiskArbitration,
    RiskArbitrationPayload,
)
from warlog_spec.proposals import (
    InvestigationSummaryProposal,
    InvestigationSummaryProposalPayload,
    NextStep,
    NextStepProposal,
    NextStepProposalPayload,
    PlaybookCandidate,
    PlaybookCandidateProposal,
    PlaybookCandidateProposalPayload,
    ProposalEnvelope,
    ProposalStepKind,
    TriageProposal,
    TriageProposalPayload,
)
from warlog_spec.action_catalog import (
    ACTION_CATALOG,
    ActionMeta,
    ParamsValidationError,
    actions_by_family,
    actions_by_reversibility,
    default_approval_for,
    load_params_schema,
    to_json_manifest,
    validate_params,
)
from warlog_spec.audit_chain import (
    CANONICALIZATION_FORMAT_V1,
    AuditChainBroken,
    canonicalize_v1,
    compute_genesis,
    compute_signature,
)
from warlog_spec.verify import (
    AuditChainVerificationError,
    VerificationReport,
    verify_audit_jsonl_file,
)
from warlog_spec.provider_conformance import (
    MOCK_PROVIDER_SCENARIO_ID,
    MOCK_VENDOR_ID,
    MockResponseVendor,
    MockVendorConnector,
    mock_provider_action_spec,
    mock_unsupported_action_spec,
    run_mock_provider_level_4,
)
from warlog_spec.ocsf import (
    OcsfDetectionFindingMapping,
    canonicalize_ocsf_event,
    hash_ocsf_event,
    map_ocsf_detection_finding,
)
from warlog_spec.enums import (
    AlertCategory,
    AlertSeverity,
    AlertSource,
    AlertStatus,
    AlertVerdict,
    CaseCategory,
    CasePriority,
    CaseSeverity,
    CaseStatus,
    EntityRole,
    EntityType,
    IOCType,
)
from warlog_spec.pack_manifest import (
    PACK_MANIFEST_VERSION,
    PackCompat,
    PackContents,
    PackDependency,
    PackKind,
    PackManifest,
    PackProvenance,
    PackPublisher,
    TrustLevel,
)
from warlog_spec.provider_abi import (
    ABI_VERSION,
    AgentCompositionKind,
    AiAgentRef,
    ApprovalDescriptor,
    ApprovalLevel,
    AuditActor,
    AuditAttestation,
    AuditConnectorRef,
    AuditRow,
    AuthDescriptor,
    AutomationActor,
    ComplianceScope,
    ConnectorAuthModel,
    ConnectorCapability,
    ConnectorCompat,
    ConnectorError,
    ConnectorKind,
    DecisionArtifactType,
    DecisionRef,
    DryRunDescriptor,
    DryRunScope,
    EgressDescriptor,
    EnrichmentDescriptor,
    ExecutionOutcome,
    ExecutionPhase,
    FailureCategory,
    FreshnessHint,
    HumanActor,
    IngressDelivery,
    IngressDescriptor,
    LifecycleDescriptor,
    ResponseActionId,
    ResponseActionResult,
    ResponseActionReversibility,
    ResponseActionScope,
    ResponseActionSpec,
    ResponseSubject,
    SelectorRepresentation,
    SignedAuditRow,
    TriggerSignalKind,
    TriggerSignalRef,
)

__version__ = "0.1.0"

__all__ = [
    # Version metadata
    "ABI_VERSION",
    "AgentCompositionKind",
    "CANONICALIZATION_FORMAT_V1",
    "PACK_MANIFEST_VERSION",
    "__version__",
    "MOCK_PROVIDER_SCENARIO_ID",
    "MOCK_VENDOR_ID",
    # ABI base + error
    "AbiConnector",
    "AbiEnricher",
    "ConnectorAbiError",
    "MockResponseVendor",
    "MockVendorConnector",
    "OcsfDetectionFindingMapping",
    # Read-side canonical artifact types (data contract)
    "AcceptedRisk",
    "AlternativeTechnique",
    "ApprovalDecision",
    "ApprovalDecisionPayload",
    "ArbitrationAuthority",
    "ArbitrationScope",
    "ArtifactCitation",
    "ArtifactConfidence",
    "ArtifactEnvelope",
    "ArtifactProducer",
    "ArtifactReviewState",
    "CanonicalArtifact",
    "CaseReturnSummary",
    "ClassificationAssessment",
    "ClassificationDecision",
    "ClosureSummary",
    "ConfidenceBand",
    "EnrichmentAssessment",
    "EnrichmentAssessmentPayload",
    "EnrichmentRequest",
    "ExtractedIOC",
    "InvestigationSummaryProposal",
    "InvestigationSummaryProposalPayload",
    "MitreAssessment",
    "MitreMapping",
    "NextStep",
    "NextStepProposal",
    "NextStepProposalPayload",
    "NormalizedEntity",
    "PlaybookCandidate",
    "PlaybookCandidateProposal",
    "PlaybookCandidateProposalPayload",
    "PolicyRef",
    "ProposalEnvelope",
    "ProposalStepKind",
    "ResponseActionRequestRef",
    "RiskArbitration",
    "RiskArbitrationPayload",
    "TriageProposal",
    "TriageProposalPayload",
    # Action catalog (executable contract for reversibility / approval defaults)
    "ACTION_CATALOG",
    "ActionMeta",
    "ParamsValidationError",
    "actions_by_family",
    "actions_by_reversibility",
    "default_approval_for",
    "load_params_schema",
    "to_json_manifest",
    "validate_params",
    # Crypto primitives (verification path)
    "AuditChainBroken",
    "AuditChainVerificationError",
    "VerificationReport",
    "canonicalize_v1",
    "compute_genesis",
    "compute_signature",
    "verify_audit_jsonl_file",
    "mock_provider_action_spec",
    "mock_unsupported_action_spec",
    "run_mock_provider_level_4",
    "canonicalize_ocsf_event",
    "hash_ocsf_event",
    "map_ocsf_detection_finding",
    # Enums
    "AlertCategory",
    "AlertSeverity",
    "AlertSource",
    "AlertStatus",
    "AlertVerdict",
    "CaseCategory",
    "CasePriority",
    "CaseSeverity",
    "CaseStatus",
    "EntityRole",
    "EntityType",
    "IOCType",
    # Pack manifest
    "PackCompat",
    "PackContents",
    "PackDependency",
    "PackKind",
    "PackManifest",
    "PackProvenance",
    "PackPublisher",
    "TrustLevel",
    # Provider ABI types (v2 trust-layer additions included)
    "AiAgentRef",
    "ApprovalDescriptor",
    "ApprovalLevel",
    "AuditActor",
    "AuditAttestation",
    "AuditConnectorRef",
    "AuditRow",
    "AuthDescriptor",
    "AutomationActor",
    "ComplianceScope",
    "ConnectorAuthModel",
    "ConnectorCapability",
    "ConnectorCompat",
    "ConnectorError",
    "ConnectorKind",
    "DecisionArtifactType",
    "DecisionRef",
    "DryRunDescriptor",
    "DryRunScope",
    "EgressDescriptor",
    "EnrichmentDescriptor",
    "ExecutionOutcome",
    "ExecutionPhase",
    "FailureCategory",
    "FreshnessHint",
    "HumanActor",
    "IngressDelivery",
    "IngressDescriptor",
    "LifecycleDescriptor",
    "ResponseActionId",
    "ResponseActionResult",
    "ResponseActionReversibility",
    "ResponseActionScope",
    "ResponseActionSpec",
    "ResponseSubject",
    "SelectorRepresentation",
    "SignedAuditRow",
    "TriggerSignalKind",
    "TriggerSignalRef",
]
