/**
 * Provider ABI — Zod schemas + inferred TypeScript types.
 *
 * Mirrors `warlog_spec.provider_abi` in the Python package. Each Zod
 * schema is the runtime validator AND the type source ; consumers
 * derive the static type via `z.infer<typeof Schema>` (re-exported as
 * a separate `type` alias here for ergonomics).
 *
 * Wire format : camelCase (matches the JSON Schemas generated by the
 * Python backend). All optional fields use `.nullable().optional()`
 * to match Pydantic's `Field(default=None)` behaviour exactly.
 */

import { z } from "zod";

import {
  ComplianceScope,
  type ComplianceScopeValue,
  SelectorRepresentation,
  type SelectorRepresentationValue,
} from "./enums.js";

export const ABI_VERSION = "1.0";
const HEX64_RE = /^[0-9a-f]{64}$/;
const HEX_RE = /^[0-9a-f]+$/;
const HEX64_MESSAGE = "must be lowercase hex sha256 (64 chars)";

// ============================================================================
// Response action catalog — 49 canonical actions
// ============================================================================

export const ResponseActionId = z.enum([
  // Device family
  "host.isolate",
  "host.unisolate",
  "host.restart",
  "host.collect_artifacts",
  "host.stop",
  "host.start",
  "host.delete",
  "process.kill",
  "process.suspend",
  "file.quarantine",
  "file.delete",
  "hash.block",
  "hash.unblock",
  // Network family
  "ip.block",
  "ip.unblock",
  "domain.block",
  "domain.unblock",
  "url.block",
  "url.unblock",
  "session.terminate",
  // Email family
  "email.quarantine",
  "email.recall",
  "email.block_sender",
  "email.unblock_sender",
  "email.release",
  // Identity family
  "user.disable",
  "user.force_logout",
  "user.reset_mfa",
  "user.revoke_tokens",
  "user.reset_password",
  "user.expire_password",
  "user.unlock",
  "user.group_remove",
  "user.delete",
  // PKI
  "cert.revoke",
  // IAM family
  "iam.role_detach",
  "iam.role_attach",
  "iam.credentials_disable",
  "iam.credentials_enable",
  "iam.credentials_rotate",
  // Key / secret family
  "key.disable",
  "key.enable",
  "key.rotate",
  "key.schedule_deletion",
  // Storage family
  "bucket.lockdown",
  "bucket.unlock",
  // Platform / case management
  "alert.acknowledge",
  "case.update_status",
  "playbook.trigger",
]);
export type ResponseActionIdValue = z.infer<typeof ResponseActionId>;

export const ResponseActionScope = z.enum([
  "endpoint",
  "identity",
  "network",
  "mail",
  "pki",
  "platform",
]);
export type ResponseActionScopeValue = z.infer<typeof ResponseActionScope>;

export const ResponseActionReversibility = z.enum([
  "reversible",
  "disruptive",
  "destructive",
  "varies",
]);
export type ResponseActionReversibilityValue = z.infer<
  typeof ResponseActionReversibility
>;

export const ApprovalLevel = z.enum(["none", "analyst", "senior", "manager"]);
export type ApprovalLevelValue = z.infer<typeof ApprovalLevel>;

export const ConnectorAuthModel = z.enum([
  "api_key",
  "oauth2_client_credentials",
  "oauth2_user_delegation",
  "mtls",
]);
export type ConnectorAuthModelValue = z.infer<typeof ConnectorAuthModel>;

export const ConnectorKind = z.enum([
  "edr",
  "siem",
  "iam",
  "email",
  "network",
  "threat_intel",
  "case_management",
  "other",
]);
export type ConnectorKindValue = z.infer<typeof ConnectorKind>;

export const IngressDelivery = z.enum(["polling", "webhook", "streaming"]);
export type IngressDeliveryValue = z.infer<typeof IngressDelivery>;

export const FreshnessHint = z.enum([
  "realtime",
  "near_realtime",
  "daily",
  "weekly",
  "unknown",
]);
export type FreshnessHintValue = z.infer<typeof FreshnessHint>;

export const DryRunScope = z.enum(["none", "egress", "ingress", "full"]);
export type DryRunScopeValue = z.infer<typeof DryRunScope>;

export const FailureCategory = z.enum([
  "auth",
  "not_found",
  "state_conflict",
  "transient",
  "policy",
]);
export type FailureCategoryValue = z.infer<typeof FailureCategory>;

export const ExecutionPhase = z.enum([
  "dry_run",
  "approval",
  "apply",
  "verify",
  "cleanup",
]);
export type ExecutionPhaseValue = z.infer<typeof ExecutionPhase>;

export const ExecutionOutcome = z.enum([
  "success",
  "failure",
  "denied",
  "expired",
  "pending_approval",
]);
export type ExecutionOutcomeValue = z.infer<typeof ExecutionOutcome>;

// ============================================================================
// ConnectorCapability — the manifest a connector publishes about itself
// ============================================================================

export const AuthDescriptor = z.object({
  model: ConnectorAuthModel,
  scopes: z.array(z.string()).default([]),
  discoveryUrl: z.string().nullable().default(null),
});
export type AuthDescriptor = z.infer<typeof AuthDescriptor>;

export const IngressDescriptor = z.object({
  produces: z.array(z.string()).default([]),
  delivery: IngressDelivery.default("polling"),
  pollingMinIntervalS: z.number().int().min(1).nullable().default(null),
});
export type IngressDescriptor = z.infer<typeof IngressDescriptor>;

export const EgressDescriptor = z.object({
  supportsResponseActions: z.array(ResponseActionId).default([]),
});
export type EgressDescriptor = z.infer<typeof EgressDescriptor>;

export const EnrichmentDescriptor = z.object({
  producesArtifactTypes: z.array(z.string()).default([]),
  supportsEntityTypes: z.array(z.string()).default([]),
  supportsIocTypes: z.array(z.string()).default([]),
  freshness: FreshnessHint.default("unknown"),
  bulkLookup: z.boolean().default(false),
});
export type EnrichmentDescriptor = z.infer<typeof EnrichmentDescriptor>;

export const DryRunDescriptor = z.object({
  supported: z.boolean().default(false),
  scope: DryRunScope.default("none"),
});
export type DryRunDescriptor = z.infer<typeof DryRunDescriptor>;

export const LifecycleDescriptor = z.object({
  supportsHealthCheck: z.boolean().default(false),
  supportsCredentialRotation: z.boolean().default(false),
  supportsPausedState: z.boolean().default(false),
});
export type LifecycleDescriptor = z.infer<typeof LifecycleDescriptor>;

export const ConnectorCompat = z.object({
  warlogSpecMin: z.string(),
  warlogSpecMax: z.string(),
});
export type ConnectorCompat = z.infer<typeof ConnectorCompat>;

export const ConnectorCapability = z.object({
  specVersion: z.literal("1.0").default("1.0"),
  connectorId: z.string().min(1).max(64),
  connectorVersion: z.string(),
  vendor: z.string(),
  kind: ConnectorKind,
  auth: AuthDescriptor,
  ingress: IngressDescriptor.default({
    produces: [],
    delivery: "polling",
    pollingMinIntervalS: null,
  }),
  egress: EgressDescriptor.default({ supportsResponseActions: [] }),
  enrichment: EnrichmentDescriptor.default({
    producesArtifactTypes: [],
    supportsEntityTypes: [],
    supportsIocTypes: [],
    freshness: "unknown",
    bulkLookup: false,
  }),
  dryRun: DryRunDescriptor.default({ supported: false, scope: "none" }),
  lifecycle: LifecycleDescriptor.default({
    supportsHealthCheck: false,
    supportsCredentialRotation: false,
    supportsPausedState: false,
  }),
  compat: ConnectorCompat,
});
export type ConnectorCapability = z.infer<typeof ConnectorCapability>;

// ============================================================================
// ResponseSubject + GDPR pseudonymization
// ============================================================================

const SelectorRepresentationEnum = z.enum([
  SelectorRepresentation.RAW,
  SelectorRepresentation.SHA256,
  SelectorRepresentation.SHA256_SALTED,
]);

export const ResponseSubject = z
  .object({
    kind: ResponseActionScope,
    selectorType: z.string(),
    selectorValue: z.string(),
    selectorRepresentation: SelectorRepresentationEnum.default("raw"),
    selectorKeyId: z.string().nullable().default(null),
  })
  .refine(
    (s) =>
      s.selectorRepresentation === "raw" ||
      (s.selectorKeyId !== null && s.selectorKeyId.length > 0),
    {
      message:
        "selectorRepresentation other than 'raw' requires a non-empty selectorKeyId",
      path: ["selectorKeyId"],
    },
  )
  .refine(
    (s) =>
      s.selectorRepresentation === "raw" || HEX64_RE.test(s.selectorValue),
    {
      message: `selectorRepresentation other than 'raw' ${HEX64_MESSAGE}`,
      path: ["selectorValue"],
    },
  );
export type ResponseSubject = z.infer<typeof ResponseSubject>;

// ============================================================================
// ResponseAction request + result + error
// ============================================================================

export const ApprovalDescriptor = z.object({
  required: z.boolean().default(true),
  level: ApprovalLevel.default("analyst"),
  rationale: z.string(),
});
export type ApprovalDescriptor = z.infer<typeof ApprovalDescriptor>;

export const ResponseActionSpec = z.object({
  specVersion: z.literal("1.0").default("1.0"),
  actionId: ResponseActionId,
  subject: ResponseSubject,
  params: z.record(z.string(), z.unknown()).default({}),
  approval: ApprovalDescriptor.default({
    required: true,
    level: "analyst",
    rationale: "",
  }),
  dryRun: z.boolean().default(false),
  idempotencyKey: z.string().min(1).max(128),
  expiresAt: z.string().datetime({ offset: true }).nullable().default(null),
});
export type ResponseActionSpec = z.infer<typeof ResponseActionSpec>;

export const ConnectorError = z.object({
  specVersion: z.literal("1.0").default("1.0"),
  category: FailureCategory,
  message: z.string(),
  retryable: z.boolean(),
  vendorCode: z.string().nullable().default(null),
  vendorMessage: z.string().nullable().default(null),
});
export type ConnectorError = z.infer<typeof ConnectorError>;

export const ResponseActionResult = z
  .object({
    specVersion: z.literal("1.0").default("1.0"),
    executionId: z.string(),
    actionId: ResponseActionId,
    outcome: ExecutionOutcome,
    subject: ResponseSubject,
    details: z.record(z.string(), z.unknown()).default({}),
    error: ConnectorError.nullable().default(null),
  })
  .superRefine((result, ctx) => {
    if (result.outcome === "failure" && result.error === null) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: "outcome='failure' requires error",
        path: ["error"],
      });
    }
    if (result.outcome === "success" && result.error !== null) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: "outcome='success' must not include error",
        path: ["error"],
      });
    }
  });
export type ResponseActionResult = z.infer<typeof ResponseActionResult>;

// ============================================================================
// Trust-layer references : DecisionRef, TriggerSignalRef, AiAgentRef
// ============================================================================

export const DecisionArtifactType = z.enum([
  "triage_proposal",
  "next_step_proposal",
  "playbook_candidate_proposal",
  "investigation_summary_proposal",
  "classification_assessment",
  "mitre_assessment",
  "enrichment_assessment",
  "closure_summary",
  "case_return_summary",
  "risk_arbitration",
  "approval_decision",
]);
export type DecisionArtifactTypeValue = z.infer<typeof DecisionArtifactType>;

export const DecisionRef = z.object({
  artifactType: DecisionArtifactType,
  artifactId: z.string().min(1),
  contentHash: z.string().regex(HEX64_RE, HEX64_MESSAGE),
});
export type DecisionRef = z.infer<typeof DecisionRef>;

export const TriggerSignalKind = z.enum([
  "ocsf_event",
  "alert",
  "ioc",
  "playbook_tick",
  "manual",
]);
export type TriggerSignalKindValue = z.infer<typeof TriggerSignalKind>;

export const TriggerSignalRef = z
  .object({
    kind: TriggerSignalKind,
    sourceId: z.string().default(""),
    contentHash: z.string().default(""),
  })
  .superRefine((signal, ctx) => {
    if (signal.kind === "manual") {
      if (signal.contentHash !== "" && !HEX64_RE.test(signal.contentHash)) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          message: `manual trigger contentHash must be empty or ${HEX64_MESSAGE}`,
          path: ["contentHash"],
        });
      }
      return;
    }
    if (signal.sourceId.length === 0) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: `trigger kind '${signal.kind}' requires sourceId`,
        path: ["sourceId"],
      });
    }
    if (!HEX64_RE.test(signal.contentHash)) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: `trigger kind '${signal.kind}' requires ${HEX64_MESSAGE} contentHash`,
        path: ["contentHash"],
      });
    }
  });
export type TriggerSignalRef = z.infer<typeof TriggerSignalRef>;

export const AgentCompositionKind = z.enum([
  "single",
  "orchestrator",
  "delegated",
  "tool_using",
  "retrieval_augmented",
  "composite",
]);
export type AgentCompositionKindValue = z.infer<typeof AgentCompositionKind>;

// Recursive schema : sub_agents is a list of AiAgentRef. Zod requires
// z.lazy + an explicit type annotation for the recursive case.
//
// Fields that the schema fills via ``.default(null)`` are typed as
// optional here so callers can omit them at construction and so the
// emitted ``.d.ts`` agrees with the schema's input type. After
// ``AiAgentRef.parse(...)`` they will always be present as ``T | null``
// — the optionality is only on the construction surface.
export type AiAgentRef = {
  model: string;
  modelVersion: string;
  systemPromptHash: string;
  agentRunId: string;
  reasoningArtifactRef?: string | null;
  // RFC-0002 extensions
  subAgents?: AiAgentRef[];
  toolsManifestHash?: string | null;
  retrievalContextRef?: string | null;
  compositionKind?: AgentCompositionKindValue | null;
};

export const AiAgentRef: z.ZodType<AiAgentRef> = z.lazy(() =>
  z.object({
    model: z.string().min(1),
    modelVersion: z.string().min(1),
    systemPromptHash: z.string().regex(HEX64_RE, HEX64_MESSAGE),
    agentRunId: z.string().min(1),
    reasoningArtifactRef: z.string().nullable().default(null),
    // RFC-0002 extensions — all optional / default-absent for v1
    // backward compatibility.
    subAgents: z.array(AiAgentRef).default([]),
    toolsManifestHash: z.string().regex(HEX64_RE, HEX64_MESSAGE).nullable().default(null),
    retrievalContextRef: z.string().nullable().default(null),
    compositionKind: AgentCompositionKind.nullable().default(null),
  }),
);

// ============================================================================
// AuditActor — discriminated union HumanActor | AutomationActor
// ============================================================================

export const HumanActor = z.object({
  kind: z.literal("human").default("human"),
  id: z.string().min(1),
});
export type HumanActor = z.infer<typeof HumanActor>;

export const AutomationActor = z.object({
  kind: z.literal("automation").default("automation"),
  id: z.string().min(1),
  agent: AiAgentRef,
});
export type AutomationActor = z.infer<typeof AutomationActor>;

export const AuditActor = z.discriminatedUnion("kind", [HumanActor, AutomationActor]);
export type AuditActor = z.infer<typeof AuditActor>;

// ============================================================================
// AuditRow + SignedAuditRow + AuditAttestation
// ============================================================================

export const AuditConnectorRef = z.object({
  id: z.string(),
  version: z.string(),
});
export type AuditConnectorRef = z.infer<typeof AuditConnectorRef>;

export const ComplianceScopeEnum = z.enum([
  ComplianceScope.NIS2,
  ComplianceScope.DORA,
  ComplianceScope.PCI_DSS_V4,
  ComplianceScope.SOX,
  ComplianceScope.HDS,
  ComplianceScope.SECNUMCLOUD,
  ComplianceScope.HIPAA,
  ComplianceScope.GDPR,
  ComplianceScope.ISO_27001,
]);
// Backwards-compat alias for snake-case lovers : both work.
export type ComplianceScopeValueLocal = z.infer<typeof ComplianceScopeEnum>;

export const AuditRow = z
  .object({
    specVersion: z.literal("1.0").default("1.0"),
    auditId: z.string(),
    executionId: z.string(),
    tenantId: z.string(),
    actor: AuditActor,
    actionId: ResponseActionId,
    subject: ResponseSubject,
    phase: ExecutionPhase,
    outcome: ExecutionOutcome,
    startedAt: z.string().datetime({ offset: true }),
    completedAt: z.string().datetime({ offset: true }).nullable().default(null),
    durationMs: z.number().int().min(0).nullable().default(null),
    error: ConnectorError.nullable().default(null),
    connector: AuditConnectorRef,
    idempotencyKey: z.string(),
    decisionRef: DecisionRef,
    triggerSignalRef: TriggerSignalRef,
    complianceScope: z.array(ComplianceScopeEnum),
    priorAuditId: z.string().nullable().default(null),
  })
  .superRefine((row, ctx) => {
    if (row.outcome === "failure" && row.error === null) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: "outcome='failure' requires error",
        path: ["error"],
      });
    }
    if (row.outcome === "success" && row.error !== null) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: "outcome='success' must not include error",
        path: ["error"],
      });
    }
  });
export type AuditRow = z.infer<typeof AuditRow>;

export const SignatureAlgorithm = z.enum([
  "HMAC-SHA256",
  "Ed25519",
  "RSASSA-PSS-SHA256",
]);
export type SignatureAlgorithmValue = z.infer<typeof SignatureAlgorithm>;

export const AuditAttestation = z.object({
  prevRowHash: z.string().regex(HEX64_RE, HEX64_MESSAGE),
  // Signature length depends on algorithm : 64 (HMAC), 128 (Ed25519),
  // 384+ (RSA-PSS). The schema accepts the union ; impl-level
  // verifiers check exact length per algorithm.
  signatureValue: z.string().min(64).max(4096).regex(HEX_RE, "must be lowercase hex"),
  algorithm: SignatureAlgorithm.default("HMAC-SHA256"),
  canonicalizationFormat: z.literal("v1").default("v1"),
  keyId: z.string().min(1),
});
export type AuditAttestation = z.infer<typeof AuditAttestation>;

export const SignedAuditRow = z.object({
  specVersion: z.literal("1.0").default("1.0"),
  payload: AuditRow,
  attestation: AuditAttestation,
});
export type SignedAuditRow = z.infer<typeof SignedAuditRow>;
